runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: false
  APP_ENV: production
  APP_KEY: base64:8Lg7kOgHthWcfVc3GWlhP2QI6ldCcA5irgxm/e+Xp/o=
  APP_NAME: "Laravel"
  LOG_LEVEL: debug
